### ISSUE TITLE
[Feature Request] Storage Zones

### ISSUE THREAD

**Issue by jspizziri** [simplesurance/terraform-provider-bunny#62]
Great work here! I've not used the provider yet but I'm very interested in managing Storage Zone resources too. I'd be interested in contributing as well. I've never worked on a provider before (although I've used lots of them) nor have I worked with the Bunny API.

My questions are:

1. Is this something you'd be interested in supporting?
2. Is it feasible from your understanding of the APIs at play?
3. Are you able to actively provide oversight, guidance, & merge/release?
4. (unrelated) have you used the provider in its current state in a prod environment?

Thanks!

**Comment by fho** [comment]
Hello @jspizziri,

1. Yes, I would accept a PR that comes with sufficient test coverage for it.
I've never used the Storage Zone API myself and we don't use it internally. Therefore further maintenance would rely mainly on the community/the PR author.
2. Yes, compared to the Pull Zone API the Storage Zone API looks simple. Representing the relation between Storage Zones and Pull Zones might be the most difficult part.
3. Yes
4. Yes, we are currently using it in production.

**Comment by jspizziri** [comment]
@fho great! thanks for the feedback. After the `bunny-go` client PR I sent over gets merged & released I'll work on a PR for this provider.
