### ISSUE TITLE
storage zone: figure out if origin_url attribute is used

### ISSUE THREAD

**Issue by fho** [simplesurance/terraform-provider-bunny#77]
The origin_url attribute of storage zones might be unused by the bunny API endpoint.
See: https://github.com/5-stones/terraform-provider-bunny/pull/1#issuecomment-1156674075

Figure out if it is used, if not remove it

**Comment by jspizziri** [comment]
@fho I got a response from the Bunny team:


> This is a bit of a special feature that's indeed not exposed via the UI. If an OriginUrl is specified on the storage zone, the storage system will first try if the file exists on the platform.
> 
> If it doesn't (internal 404), the request will be proxied to the specified OriginUrl instead.

With that said, I think the task here is to enhance the documentation of that property so that people understand what it is and what it can do.
