### ISSUE TITLE
resource bunny_pullzone doesn't support import

### ISSUE THREAD

**Issue by knyttl** [simplesurance/terraform-provider-bunny#78]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
$ terraform -v
Terraform v1.2.2
on darwin_amd64
+ provider registry.terraform.io/simplesurance/bunny v0.7.1
```

### Affected Resource(s)
`bunny_pullzone`

### Panic Output
```
$ terraform import bunny_pullzone.my-pullzone my-pullzone
bunny_pullzone.my-pullzone: Importing from ID "my-pullzone"...

│ Error: resource my-pullzone doesn't support import
```
### Expected Behavior
I should be able to import the Bunny pullzone.

### Actual Behavior
Pullzone cannot be imported.

### Steps to Reproduce
1. Create a pullzone in the UI
2. Try to import it in Terraform

**Comment by fho** [comment]
@knyttl support for importing pullzones was merged to main and will be part of the next release

**Comment by knyttl** [comment]
THANKS!
