### ISSUE TITLE
storagezone: Adding new replication regions 

### ISSUE THREAD

**Issue by roman-dymov-faraway** [simplesurance/terraform-provider-bunny#94]
Hello

I have created a storage zone and pull zone manually. Next, I want to import it to terraform. 

```hcl
Error: 1 error occurred:
│       * 'replication_regions' can be added but not removed once the zone has been created.
│ This error occurred when attempting to remove values ["NY" "SG" "SE" "DE" "UK"] from 'replication_regions'.
```

When I try to add these regions to terraform code, I have the next errors

```hcl
Error: expected replication_regions to be one of [DE NY LA SG SYD], got GB
```

I think your need to add new bunny regions. What do we have? 

Europe:
- Falkenstein (DE)
- London (GB)
- Stockholm (SE)

North America:
- Los Angeles (US). Your name is LA 
- New York (US). Your name is NY 

Asia & Oceania:
- Sydney (AU). Your name is SYD
- Singapore (SG)

LATAM: 
- Sao Paulo (BR)

So we have the next regions: DE, LA, NY, SYD, SG and you need to add GB, SE, and BR regions. I am not a programmer, but think it could be added to

https://github.com/simplesurance/terraform-provider-bunny/blob/main/internal/provider/resource_storagezone.go#L65

Thank you

**Comment by fho** [comment]
Hello Roman,

yes, looks like it! :-)
In the [bunny API doc](https://docs.bunny.net/reference/storagezonepublic_add) they are not listed. It is sometimes not up2date.

New replication regions needs to be added to to https://github.com/simplesurance/terraform-provider-bunny/blob/48f03dde26efd529a91d9251de432d4d9e517c59/internal/provider/resource_storagezone.go#L65
If there are also new storage zone regions they need to be listed in https://github.com/simplesurance/terraform-provider-bunny/blob/48f03dde26efd529a91d9251de432d4d9e517c59/internal/provider/resource_storagezone.go#L56.

If you can create PR with that change, I can review it  + create new provider release soon.

**Comment by roman-dymov-faraway** [comment]
I created [PR](https://github.com/simplesurance/terraform-provider-bunny/pull/95), but I think we need to do something else.

Such regions as Sydney (AU/SYD), Singapore (SG), and Sao Paulo (BR) must contain at least one of the "replication regions" ( I have checked it with BunnyCDN API).  Can you add some checks to resourceStorageZoneCreate like:

```go
func stringInSlice(a string, list []string) bool {
    for _, b := range list {
        if b == a {
            return true
        }
    }
    return false
}

func CreatingRegionWithoutReplicationRegionError(region string,  allRegions []string) error {
	const message = "'%s' region needs to have at least one replication region.\n" +
		"Please add on of avaliable replication region %s.\n" +
	return fmt.Errorf(message, region, allRegions)
}

if stringInSlice(getStrPtr(d, keyRegion), ["SYD", "SG", "BR"]) {
  return CreatingRegionWithoutReplicationRegionError(getStrPtr(d, keyRegion), ["SYD", "SG", "BR"])
}
```
Or you can create this array in the structure. Next, add new elements to it and check it further in the code.
As I said earlier, I am not a golang programmer, so don't judge too harshly

**Comment by roman-dymov-faraway** [comment]
My colleague helped me with the code. I ran "make install; make testacc" and it looks okay. Please check
